name: LFPAnalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - pip
  - requests
  - mne
  - mne-connectivity
  - seaborn
  - statsmodels
  - numba
  - ipython
  - ipyevents
  - ipywidgets
  - ipykernel
  - openpyxl
  - dcor
  - llvmlite
  - pyyaml
  - sparse
  - tabulate
  - levenshtein
  - pycatch22
  - wheel
  - notebook
  - h5io
  - tensorpac
  - neurodsp=2.2.0
  - fooof=1.0.0