name: LFPAnalysis
channels:
  - default 
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex 
  - aom   
  - appdirs   
  - asttokens   
  - backcall   
  - blas   
  - bottleneck   
  - brotli   
  - brotli-bin   
  - brotlipy   
  - bzip2   
  - c-ares   
  - ca-certificates   
  - cached-property   
  - cached_property   
  - certifi   
  - cffi   
  - cftime   
  - charset-normalizer   
  - colorama   
  - contourpy   
  - cryptography   
  - curl   
  - cycler   
  - dbus   
  - debugpy   
  - decorator   
  - double-conversion   
  - eigen   
  - entrypoints   
  - executing   
  - expat   
  - ffmpeg   
  - fftw   
  - font-ttf-dejavu-sans-mono   
  - font-ttf-inconsolata   
  - font-ttf-source-code-pro   
  - font-ttf-ubuntu   
  - fontconfig   
  - fonts-conda-ecosystem   
  - fonts-conda-forge   
  - fonttools   
  - freetype   
  - gettext   
  - giflib   
  - gl2ps   
  - glib   
  - gmp   
  - gnutls   
  - gst-plugins-base   
  - gstreamer   
  - h5netcdf   
  - h5py   
  - hdf4   
  - hdf5   
  - icu   
  - idna   
  - imageio   
  - intel-openmp   
  - ipykernel   
  - ipython   
  - jedi   
  - jinja2   
  - joblib   
  - jpeg   
  - jsoncpp   
  - jupyter_client   
  - jupyter_core   
  - kiwisolver   
  - krb5   
  - lame   
  - lcms2   
  - ld_impl_linux-64   
  - lerc   
  - libbrotlicommon   
  - libbrotlidec   
  - libbrotlienc   
  - libclang   
  - libcurl   
  - libdeflate   
  - libdrm   
  - libedit   
  - libev   
  - libevent   
  - libffi   
  - libgcc-ng   
  - libgfortran-ng   
  - libgfortran5   
  - libhwloc   
  - libidn2   
  - libllvm10   
  - libnetcdf   
  - libnghttp2   
  - libogg   
  - libpciaccess   
  - libpng   
  - libpq   
  - libsodium   
  - libsqlite   
  - libssh2   
  - libstdcxx-ng   
  - libtasn1   
  - libtheora   
  - libtiff   
  - libunistring   
  - libuuid   
  - libva   
  - libvorbis   
  - libvpx   
  - libwebp   
  - libwebp-base   
  - libxcb   
  - libxkbcommon   
  - libxml2   
  - libxslt   
  - libzip   
  - libzlib   
  - llvm-openmp   
  - loguru   
  - lz4-c   
  - markupsafe   
  - matplotlib   
  - matplotlib-base   
  - matplotlib-inline   
  - mkl   
  - mkl-service   
  - mkl_fft   
  - mkl_random   
  - mne-base   
  - mne-connectivity   
  - munkres   
  - ncurses   
  - nest-asyncio   
  - netcdf4   
  - nettle   
  - nspr   
  - nss   
  - numexpr   
  - numpy   
  - numpy-base   
  - openh264   
  - openssl   
  - p11-kit   
  - packaging   
  - pandas   
  - parso   
  - pcre   
  - pexpect   
  - pickleshare   
  - pillow   
  - pip   
  - ply   
  - pooch   
  - proj   
  - prompt-toolkit   
  - psutil   
  - ptyprocess   
  - pugixml   
  - pure_eval   
  - pycparser   
  - pygments   
  - pyopenssl   
  - pyparsing   
  - pyqt   
  - pyqt5-sip   
  - pysocks   
  - python   
  - python-dateutil   
  - python_abi   
  - pytz   
  - pyvista   
  - pyvistaqt   
  - pyzmq   
  - qt-main   
  - qt-webengine   
  - qtpy   
  - qtwebkit   
  - readline   
  - requests   
  - scikit-learn   
  - scipy   
  - scooby   
  - seaborn   
  - setuptools   
  - sip   
  - six   
  - sqlite   
  - stack_data   
  - svt-av1   
  - tbb   
  - tbb-devel   
  - threadpoolctl   
  - tk   
  - toml   
  - tornado   
  - tqdm   
  - traitlets   
  - typing_extensions   
  - tzdata   
  - urllib3   
  - utfcpp   
  - vtk   
  - wcwidth   
  - wheel   
  - x264   
  - x265   
  - xarray   
  - xorg-fixesproto   
  - xorg-kbproto   
  - xorg-libice   
  - xorg-libsm   
  - xorg-libx11   
  - xorg-libxext   
  - xorg-libxfixes   
  - xorg-libxt   
  - xorg-xextproto   
  - xorg-xproto   
  - xz   
  - zeromq   
  - zlib   
  - zstd   
  - pip: 
    - astropy==5.2
    - autoreject==0.4.0
    - bokeh==3.0.3
    - commonmark==0.9.1
    - et-xmlfile==1.1.0
    - future==0.18.2 
    - h5io==0.1.7
    - hypyp==0.4.0b6
    - meshio==5.3.4
    - mistune==2.0.4
    - neurodsp==2.2.1
    - openpyxl==3.0.10
    - patsy==0.5.3 
    - pyerfa==2.0.0.1
    - pymatreader==0.0.30
    - pyyaml==6.0
    - rich==12.6.0
    - statsmodels==0.13.5
    - xmltodict==0.13.0 
    - xyzservices==2022.9.0